version: "3.8"

services:
  app:
    # build: .
    image: 386jp/public_ip_report:latest
    restart: always
    environment:
      FETCH_INTERVAL: ${FETCH_INTERVAL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      ALWAYS_REPORT: ${ALWAYS_REPORT}
      TZ: ${TZ}
